{{- if .Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccf-app.fullname" . }}-api
  labels:
    {{- include "ccf-app.componentMetadataLabels" (dict "root" . "name" "api" "component" .Values.api) | nindent 4 }}
data:
  APP_PORT: "{{ .Values.api.service.port }}"
  CCF_DB_DRIVER: "postgres"
  CCF_DB_HOST: {{ if .Values.database.local.enabled }}"{{ include "ccf-app.fullname" . }}-postgresql"{{ else }}"{{ coalesce .Values.database.external.host .Values.database.external.hostname }}"{{ end }}
  CCF_DB_PORT: "{{ if .Values.database.local.enabled }}5432{{ else }}{{ .Values.database.external.port }}{{ end }}"
  CCF_DB_NAME: "{{ if .Values.database.local.enabled }}{{ .Values.database.local.database }}{{ else }}{{ .Values.database.external.database }}{{ end }}"
  CCF_DB_USER: "{{ if .Values.database.local.enabled }}{{ .Values.database.local.username }}{{ else }}{{ .Values.database.external.username }}{{ end }}"
  CCF_JWT_PRIVATE_KEY: "/var/ccf/private_key/private_key.pem"
  CCF_JWT_PUBLIC_KEY: "/var/ccf/public_key/public_key.pem"
  CCF_WEB_BASE_URL: {{ .Values.api.webBaseUrl | quote }}
  CCF_ENVIRONMENT: {{ .Values.api.environment | default "production" | quote }}
  CCF_API_ALLOWED_ORIGINS: {{ if .Values.api.corsOrigins }}{{ .Values.api.corsOrigins | join "," | quote }}{{ else }}"http://localhost:3000"{{ end }}
  {{- range $key, $val := .Values.api.extraConfig }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- if .Values.api.sso.enabled }}
  CCF_SSO_CONFIG: "/etc/ccf/sso.yaml"
  {{- end }}
  {{- if .Values.api.email.enabled }}
  CCF_EMAIL_CONFIG: "/etc/ccf/email.yaml"
  {{- end }}
  {{- if .Values.api.workflow.enabled }}
  CCF_WORKFLOW_CONFIG: "/etc/ccf/workflow.yaml"
  {{- end }}
{{- end }}
