{{- if and .Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccf-app.fullname" . }}-api-authz
  labels:
    {{- include "ccf-app.componentMetadataLabels" (dict "root" . "name" "api" "component" .Values.api) | nindent 4 }}
data:
  authz-roles.yaml: |
    {{- toYaml (default (dict) .Values.api.authz.roleAssignments) | nindent 4 }}
{{- end }}
