{{- if .Values.ui.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccf-app.fullname" . }}-ui
  labels:
    {{- include "ccf-app.componentMetadataLabels" (dict "root" . "name" "ui" "component" .Values.ui) | nindent 4 }}
data:
  config.json: |
    {
      "API_URL": {{ .Values.ui.apiUrl | quote }}
    }
{{- end }}
