{{- $jwt := include "ccf-app.jwtRuntimeConfig" . | fromYaml -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccf-app.fullname" . }}-initial-user-password
type: Opaque
data:
  password: {{ include "ccf-app.initialUserPasword" . }}
{{- if eq $jwt.source "generated" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccf-app.fullname" . }}-jwt-private-key
type: Opaque
data:
  private_key.pem: {{ genPrivateKey "rsa" | b64enc }}
{{- end }}
