{{- if and .Values.dex.enabled .Values.dex.clientSecret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccf-app.fullname" . }}-dex
  labels:
    {{- include "ccf-app.componentMetadataLabels" (dict "root" . "name" "dex" "component" .Values.dex) | nindent 4 }}
type: Opaque
data:
  {{ include "ccf-app.dexClientSecretKey" . }}: {{ include "ccf-app.dexClientSecretB64" . | quote }}
{{- end }}
