{{- if has (include "ccf-app.initialUserPasswordSource" .) (list "value" "seed") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccf-app.fullname" . }}-initial-user-password
type: Opaque
data:
  password: {{ include "ccf-app.initialUserPassword" . | b64enc }}
{{- end }}
