{{- if .Values.database.local.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccf-app.fullname" . }}-psql
  labels:
    {{- include "ccf-app.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ include "ccf-app.psqlPasswordB64" . }}
{{- end }}
