{{- if and .Values.database.local.enabled (has (include "ccf-app.psqlPasswordSource" .) (list "value" "seed")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccf-app.fullname" . }}-psql
  labels:
    {{- include "ccf-app.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ include "ccf-app.psqlPassword" . | b64enc }}
{{- end }}
