{{- if .Values.api.enabled }}
{{- $ssoCreateSecret := and .Values.api.sso.enabled .Values.api.sso.createSecret }}
{{- $emailCreateSecret := and .Values.api.email.enabled .Values.api.email.createSecret }}
{{- $slackCreateSecret := and .Values.api.slack.enabled .Values.api.slack.createSecret }}
{{- if or $ssoCreateSecret $emailCreateSecret $slackCreateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccf-app.fullname" . }}-api-config
  labels:
    {{- include "ccf-app.componentMetadataLabels" (dict "root" . "name" "api" "component" .Values.api) | nindent 4 }}
type: Opaque
data:
  {{- if $ssoCreateSecret }}
  {{- range $key, $val := .Values.api.sso.providers }}
  {{- if $val.enabled }}
  {{- if $val.clientId }}
  CCF_SSO_PROVIDERS_{{ $key | upper }}_CLIENT_ID: {{ $val.clientId | b64enc | quote }}
  {{- end }}
  {{- if $val.clientSecret }}
  CCF_SSO_PROVIDERS_{{ $key | upper }}_CLIENT_SECRET: {{ $val.clientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if $emailCreateSecret }}
  {{- if and .Values.api.email.providers.smtp .Values.api.email.providers.smtp.enabled }}
  CCF_EMAIL_PROVIDERS_SMTP_PASSWORD: {{ .Values.api.email.providers.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.api.email.providers.ses .Values.api.email.providers.ses.enabled }}
  {{- if .Values.api.email.providers.ses.accessKeyId }}
  CCF_EMAIL_PROVIDERS_SES_ACCESS_KEY_ID: {{ .Values.api.email.providers.ses.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.api.email.providers.ses.secretAccessKey }}
  CCF_EMAIL_PROVIDERS_SES_SECRET_ACCESS_KEY: {{ .Values.api.email.providers.ses.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.api.email.providers.ses.sessionToken }}
  CCF_EMAIL_PROVIDERS_SES_SESSION_TOKEN: {{ .Values.api.email.providers.ses.sessionToken | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if $slackCreateSecret }}
  CCF_SLACK_TOKEN: {{ .Values.api.slack.token | b64enc | quote }}
  {{- if .Values.api.slack.clientId }}
  CCF_SLACK_CLIENT_ID: {{ .Values.api.slack.clientId | b64enc | quote }}
  CCF_SLACK_CLIENT_SECRET: {{ .Values.api.slack.clientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
