apiVersion: v1
kind: Service
metadata:
  name: {{ include "ccf-app.fullname" . }}
  labels:
    {{- include "ccf-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ccf-app.selectorLabels" . | nindent 4 }}
{{- if .Values.database.local.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ccf-app.fullname" . }}-postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/type: database
{{- end }}