apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccf-agent.fullname" . }}-config
  labels:
    {{- include "ccf-agent.labels" . | nindent 4 }}
data:
  config.yml: |
    daemon: {{ .Values.agent.daemon }}
    verbosity: {{ .Values.agent.verbosity }}
    api:
      url: {{ .Values.agent.api.url }}
      {{- with .Values.agent.api.auth }}
      auth:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    agent_evidence:
      enabled: {{ .Values.agent.agentEvidence.enabled }}
      interval: {{ .Values.agent.agentEvidence.interval | default "1h" }}
    {{- if .Values.agent.plugins }}
    plugins:
      {{- toYaml .Values.agent.plugins | nindent 6 }}
    {{- end }}
