{{- include "ccf-agent.validateAuthConfig" . }}
{{- if and .Values.agent.api.auth.enabled .Values.agent.api.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccf-agent.fullname" . }}-auth
  labels:
    {{- include "ccf-agent.labels" . | nindent 4 }}
type: Opaque
data:
  CCF_API_AUTH_CLIENT_ID: {{ .Values.agent.api.auth.clientId.value | b64enc | quote }}
  CCF_API_AUTH_CLIENT_SECRET: {{ .Values.agent.api.auth.clientSecret.value | b64enc | quote }}
{{- end }}
